package hisense.code.model;


import hisense.code.model.base.BaseTUser;
import hisense.code.utils.StringUtils;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
    public static final TUser dao = new TUser().dao();

    public List<TUser> getAllList(TUser user) {
        String sql = "select * from t_user where 1=1";
        if (user.getId() != null) {
            sql += String.format("and id = %s", user.getId());
        }

        if (StringUtils.isNotNull(user.getUsername())) {
            sql += String.format("and username = %s", user.getUsername());
        }

        if (StringUtils.isNotNull(user.getPassword())) {
            sql += String.format("and password = %s", user.getPassword());
        }

        List<TUser> list = dao.find(sql);
        return list;
    }
}
