package hisense.code.model.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

public final class PeopleDto {
  private PeopleDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeopleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:People)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 numberP = 1;</code>
     */
    int getNumberP();

    /**
     * <code>string nameP = 2;</code>
     */
    String getNameP();
    /**
     * <code>string nameP = 2;</code>
     */
    com.google.protobuf.ByteString
        getNamePBytes();
  }
  /**
   * Protobuf type {@code People}
   */
  public  static final class People extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:People)
      PeopleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use People.newBuilder() to construct.
    private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private People() {
      numberP_ = 0;
      nameP_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private People(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              numberP_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              nameP_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PeopleDto.internal_static_People_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PeopleDto.internal_static_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              People.class, Builder.class);
    }

    public static final int NUMBERP_FIELD_NUMBER = 1;
    private int numberP_;
    /**
     * <code>int32 numberP = 1;</code>
     */
    public int getNumberP() {
      return numberP_;
    }

    public static final int NAMEP_FIELD_NUMBER = 2;
    private volatile Object nameP_;
    /**
     * <code>string nameP = 2;</code>
     */
    public String getNameP() {
      Object ref = nameP_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nameP_ = s;
        return s;
      }
    }
    /**
     * <code>string nameP = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNamePBytes() {
      Object ref = nameP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nameP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numberP_ != 0) {
        output.writeInt32(1, numberP_);
      }
      if (!getNamePBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nameP_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numberP_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numberP_);
      }
      if (!getNamePBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nameP_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof People)) {
        return super.equals(obj);
      }
      People other = (People) obj;

      boolean result = true;
      result = result && (getNumberP()
          == other.getNumberP());
      result = result && getNameP()
          .equals(other.getNameP());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBERP_FIELD_NUMBER;
      hash = (53 * hash) + getNumberP();
      hash = (37 * hash) + NAMEP_FIELD_NUMBER;
      hash = (53 * hash) + getNameP().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static People parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static People parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static People parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static People parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static People parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static People parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static People parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static People parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static People parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static People parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static People parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static People parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(People prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code People}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:People)
        PeopleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PeopleDto.internal_static_People_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PeopleDto.internal_static_People_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                People.class, Builder.class);
      }

      // Construct using PeopleDto.People.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        numberP_ = 0;

        nameP_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PeopleDto.internal_static_People_descriptor;
      }

      public People getDefaultInstanceForType() {
        return People.getDefaultInstance();
      }

      public People build() {
        People result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public People buildPartial() {
        People result = new People(this);
        result.numberP_ = numberP_;
        result.nameP_ = nameP_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof People) {
          return mergeFrom((People)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(People other) {
        if (other == People.getDefaultInstance()) return this;
        if (other.getNumberP() != 0) {
          setNumberP(other.getNumberP());
        }
        if (!other.getNameP().isEmpty()) {
          nameP_ = other.nameP_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        People parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (People) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numberP_ ;
      /**
       * <code>int32 numberP = 1;</code>
       */
      public int getNumberP() {
        return numberP_;
      }
      /**
       * <code>int32 numberP = 1;</code>
       */
      public Builder setNumberP(int value) {
        
        numberP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberP = 1;</code>
       */
      public Builder clearNumberP() {
        
        numberP_ = 0;
        onChanged();
        return this;
      }

      private Object nameP_ = "";
      /**
       * <code>string nameP = 2;</code>
       */
      public String getNameP() {
        Object ref = nameP_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nameP_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nameP = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNamePBytes() {
        Object ref = nameP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nameP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nameP = 2;</code>
       */
      public Builder setNameP(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nameP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nameP = 2;</code>
       */
      public Builder clearNameP() {
        
        nameP_ = getDefaultInstance().getNameP();
        onChanged();
        return this;
      }
      /**
       * <code>string nameP = 2;</code>
       */
      public Builder setNamePBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nameP_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:People)
    }

    // @@protoc_insertion_point(class_scope:People)
    private static final People DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new People();
    }

    public static People getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<People>
        PARSER = new com.google.protobuf.AbstractParser<People>() {
      public People parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new People(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<People> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<People> getParserForType() {
      return PARSER;
    }

    public People getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_People_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_People_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014People.proto\"(\n\006People\022\017\n\007numberP\030\001 \001(" +
      "\005\022\r\n\005nameP\030\002 \001(\tB\013B\tPeopleDtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_People_descriptor,
        new String[] { "NumberP", "NameP", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
