package hisense.code.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTUser<M extends BaseTUser<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}

	public String getUsername() {
		return getStr("username");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}

	public String getPassword() {
		return getStr("password");
	}

	public M setSex(String sex) {
		set("sex", sex);
		return (M)this;
	}

	public String getSex() {
		return getStr("sex");
	}


}
